# data-integration/k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
data:
  alpha-vantage-api-key: QUJDMTIzREVGNDU2R0hJNzg5  # Base64 encoded API key

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  access-key: QUtJQUlPU0ZPRE5ONw==  # Base64 encoded AWS access key
  secret-key: d0phbGxyZEVvQ0pLbmVTL0xTRkFLRU5vdFJlYWwvQUtFS2V5  # Base64 encoded AWS secret key