# kubernetes/manifests/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  db_password: UGFzc3dvcmQxMjMh  # base64 encoded "Password123!"
  api_key: U0VDUkVUS0VZ          # base64 encoded "SECRETKEY"