# kubernetes/manifests/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-web
spec:
  type: LoadBalancer
  selector:
    app: frontend-web
  ports:
  - port: 80
    targetPort: 80